# Generated by Django 3.0.2 on 2020-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_name', models.CharField(max_length=50)),
                ('ev_desc', models.CharField(max_length=2000)),
                ('ev_date', models.DateTimeField()),
                ('ev_reg_end', models.DateField()),
                ('ev_img', models.ImageField(upload_to='pics')),
                ('ev_availability', models.BooleanField(default=True)),
                ('ev_year', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='hof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hof_name', models.CharField(max_length=50)),
                ('hof_desc', models.TextField()),
                ('hof_awards', models.CharField(max_length=5000)),
                ('hof_img', models.ImageField(upload_to='pics')),
                ('hof_yr', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_name', models.CharField(max_length=50)),
                ('serv_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_name', models.CharField(max_length=50)),
                ('tm_exp', models.CharField(max_length=50)),
                ('tm_desc', models.CharField(max_length=5000)),
                ('tm_img', models.ImageField(upload_to='pics')),
                ('tm_ph', models.IntegerField(max_length=12)),
                ('tm_mail', models.EmailField(max_length=250)),
            ],
        ),
    ]
